generator_task:
  description: >
    You will generate PIQ questions that are standard and create some great unique and creative answers for all of them on a {program}-specific basis.
  expected_output: >
    A set of 8 questions and answers for the college {program} application. Please make sure that the questions are standard and the answers are unique and creative and 
    are specific to UC college system.
  agent: college_question_generator


